---
# tasks file for apptainer
- name: install packages
  become: yes
  apt:
    pkg:
      - software-properties-common
    state: latest


- name: add repository
  become: yes
  apt_repository:
    repo: ppa:apptainer/ppa


- name: install packages
  become: yes
  apt:
    pkg:
      - apptainer
    state: latest
    update_cache: yes

